### ISSUE TITLE
There is no website

### ISSUE THREAD

**Issue by gyanl** [gyanl/MAITProgrammersGuild#1]
# hacktoberfest

Make an index.html page

**Comment by donniepropst** [comment]
@gyanl Mind if I help knock a few of these out for hacktoberfest?

**Comment by gauravdesale** [comment]
I can make this but can someone send me the details I need to put on the website I will take care of the ui

**Comment by tarlepp** [comment]
Hmm, is this "website" for what? business, pleasure, pyramid scam, criminal activities, isis, etc. ?

**Comment by grant-park** [comment]
pull requested an index.html, please tell us more about the content and we can expand on it

**Comment by gyanl** [comment]
Hey @sungjp - I've added some details about the website in the readme, but I was mostly intending my classmates to help out with the website. Thanks for setting up the index page though! I'll be able to use this as a great example for how Open Sourcing your projects can be great - people here tend to think of their code as "their code". I've added you to the contributors in the readme and the project is live here : https://gyanl.github.io/MAITProgrammersGuild/

**Comment by gyanl** [comment]
@tarlepp - Sorry if this felt like a farce, just trying to get a bunch of people who've never used Github and don't really want to, to start making contributions.

**Comment by gauravdesale** [comment]
sure no problem what is the next thing I have to do for now

**Comment by gauravdesale** [comment]
Like this is an issue for the website of hacktober not being complete
enough right so I can make a new one but i need content to put on the
website

**Comment by gyanl** [comment]
@gauravdesale : This is an internal website for my college programming society, but you're welcome to contribute any improvements. Right now it's very much work in progress.
