### ISSUE TITLE
There is no javascript

### ISSUE THREAD

**Issue by gyanl** [gyanl/MAITProgrammersGuild#2]
Create script.js & add script tag in html file

**Comment by hkveeranki** [comment]
@gyanl what should be functions in script.js ? and where is the html file ?

**Comment by grant-park** [comment]
pull requested a script.js

**Comment by gyanl** [comment]
Thanks, @sungjp!
@harry-7 : I plan to use Google Analytics, and I'd like the javascript code to be in a separate file.
