### ISSUE TITLE
There is no logo

### ISSUE THREAD

**Issue by gyanl** [gyanl/MAITProgrammersGuild#3]
If we have a website it should have a logo

**Comment by saurabhiiit** [comment]
Ways to Get a Logo for Your Website
 If you  don't have a logo for your website,  you really should hire a professional logo design company to create it for you.

Tools You Will Need for designing 
1. Painting Program - You will basically need some sort of drawing program.
2. Fonts - You will probably also need to have a selection of different fonts (typefaces) on your system to use for your logo.

**Comment by gyanl** [comment]
![mait-tech-bw](https://cloud.githubusercontent.com/assets/9626697/18939242/7b97a094-861c-11e6-883a-3cf50bead60a.png)

Hey @saurabhiiit , I made something. Can you give me feedback?

**Comment by saurabhiiit** [comment]
@gyanl It is very good design I was also thinking of designing like that.
The fonts and design is very much appropriate according to the name and it looks cool :thumbsup:
