### ISSUE TITLE
There is no favicon

### ISSUE THREAD

**Issue by gyanl** [gyanl/MAITProgrammersGuild#4]
Favicon toh banta hai

**Comment by saurabhiiit** [comment]
Creating Favicon.ico file
    Create an image 16X16 pixels in size. Yes, it is really small and you can't really draw much in it. You should also restrict yourself to the standard Windows 16 colours, although I suspect that 256 colours will work fine.

```
If you like, you can also create a 32X32 pixel icon, which will be scaled to size for the Favorites menu and the location bar. You can even put both 16X16 and 32X32 pixel icons into the same icon file. Windows will use the former for its menus and the latter when the user opens up a folder that is set to display large icons. It's probably not really necessary to do this if you can't be bothered.

Save the image as an ICO file (named "favicon.ico", of course).

Upload it to your website. You don't need to upload one to every directory of your site if you don't want to waste space — simply put it in your root directory and the web browsers that support favicons will apparently locate it eventually. You can also upload it into your images directory, but you will need to modify your web pages if you do. See later in this article for more information on this.
```

If you have placed your favicon.ico file in a location other than the current web directory (relative to your web page) or the root directory, you have to help your visitors' browser locate the favicon file by specifying it with a tag like the following in the <head> section of your web page. 
 <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" /> 

You should replace "/favicon.ico" in the above example with the actual location of your favicon.ico file, for example, "/images/favicon.ico" if you have placed it in your "/images/" directory.

**Comment by grant-park** [comment]
added a random favicon

**Comment by gyanl** [comment]
Thanks, @sungjp and @saurabhiiit!
